@startuml

sprite $bProcess jar:archimate/business-process
sprite $aService jar:archimate/application-service
sprite $aComponent jar:archimate/application-component
sprite $bEvent jar:archimate/business-event
sprite $aEquipment jar:archimate/physical-equipment

title 形式语言概念模型

node  "名称" #TECHNOLOGY{

    node  "通名" #TECHNOLOGY{

        node  "原始通名" as 原始通名 #TECHNOLOGY{
            archimate #Business "原子"
            archimate #Business "结构"
            archimate #Business "运动"
            archimate #Business "圆周运动"
            archimate #Business "职业"
        }

        node  "关系通名" as 关系通名 #TECHNOLOGY{
            archimate #Business "就职关系（员工,单位）"

            node  "语法关系" as 语法关系 #TECHNOLOGY{
                archimate #Business "元素集合关系（元素,集合）"
                archimate #Business "父子集关系（元素,集合）"
                archimate #Business "同属集合关系（元素,元素）"
                archimate #Business "同义关系（名称,名称）"
            }
        }

        node  "组合通名" as 组合通名  #TECHNOLOGY{
            archimate #Business "原子的结构(x.y)"
        }

        原始通名 --> 组合通名:生成
    }

    node  "专名" #TECHNOLOGY{
        node  "普通专名" #TECHNOLOGY{
            archimate #Business "张三"
            archimate #Business "特朗普"
            archimate #Business "二战"
        }

        node  "代词" #TECHNOLOGY{
            archimate #Business "这个"
            archimate #Business "那个"
        }
    }
}

node  "事实" as 事实 #TECHNOLOGY{

    node  "通名事实" as 通名事实 #TECHNOLOGY{

    }

    node  "专名事实" as 专名事实 #TECHNOLOGY{

    }
    专名 --> 专名事实:赋值
    通名 --> 通名事实:赋值

}



node  "记忆语境" as 记忆语境 #TECHNOLOGY{

}
事实 --> 记忆语境:学习形成

node  "意图语境" as 意图语境 #TECHNOLOGY{

}
事实 --> 意图语境:运用时形成



legend left

建立一个能够搜索、自动生成相似结构的语义网，实现类比查询(推理)

系统必须具备什么样的能力才能学习语言

通名，联想建立已有通名到新通名的理解路径
专名，联想建立联系，重要的是建立事实

事实的集合形成语境

名称的关联形成事实
事实的关联形成语境

语义理解时，根据记忆语境预测意图，根据意图给出输出

endlegend

@enduml