@startuml

sprite $bProcess jar:archimate/business-process
sprite $aService jar:archimate/application-service
sprite $aComponent jar:archimate/application-component
sprite $bEvent jar:archimate/business-event
sprite $aEquipment jar:archimate/physical-equipment

title 形式语言模型

node  "名称" #TECHNOLOGY{

    node  "通名" #TECHNOLOGY{

        node  "分类通名" as 分类通名 #TECHNOLOGY{
            archimate #Business "原子"
            archimate #Business "结构"
            archimate #Business "运动"
            archimate #Business "圆周运动"
            archimate #Business "职业"
        }

        node  "组合通名" as 组合通名  #TECHNOLOGY{
            archimate #Business "原子的结构(x.y)"
        }

        node  "关系通名" as 关系通名 #TECHNOLOGY{
            archimate #Business "就职关系（员工,单位）"
        }

        node  "语法关系" as 语法关系 #TECHNOLOGY{
            archimate #Business "元素集合关系（元素,集合）"
            archimate #Business "父子集关系（元素,集合）"
            archimate #Business "同属集合关系（元素,元素）"
        }
    }

    node  "专名" #TECHNOLOGY{
        node  "普通专名" #TECHNOLOGY{

        }

        node  "代词" #TECHNOLOGY{

        }

        node  "限定摹状词" #TECHNOLOGY{

        }
    }
}

node  "真值语句（事实）" as 真值语句 #TECHNOLOGY{

}

语法关系 --> 真值语句:赋值得到







legend left

建立一个能够搜索、自动生成相似结构的语义网，实现类比查询(推理)


endlegend

@enduml